# Generated by Django 3.0.6 on 2020-05-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('contest_id', models.CharField(max_length=20)),
                ('contest_type', models.IntegerField(choices=[(1, 'ABC'), (2, 'ARC'), (3, 'AGC'), (4, 'Others-Rated'), (5, 'Others-Unrated')])),
                ('exec_time', models.IntegerField()),
                ('code_size', models.IntegerField()),
            ],
            options={
                'db_table': 'problem',
            },
        ),
    ]
